spring:
  profiles:
    active: local

---
server:
  port: 9002

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/async-saga
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: heedong
    password: 1q2w3e4r!@
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password: 
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
