version: '3'
services:
  mysql:
    platform: linux/x86_64
    container_name:  mysql_test_8.0
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: "testdb"
      TZ: Asia/Seoul
    ports:
      - "13306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"