version: '3'
services:
  redis:
    container_name: redis_test
    image: redis:alpine
    hostname: redis_boot
    ports:
      - "16379:6379"
    command: redis-server --port 6379
    labels:
      - "name=redis"
      - "mode=standalone"