spring:
  profiles:
    active: local

---
server:
  port: 9000

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/async-saga
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: heedong
    password: 1q2w3e4r!@
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
  kafka:
    topic:
      order: order
      payment: payment
    consumer:
      bootstrap-servers: { your bootstrap server uri }
      group-id: { kafka group id }
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: { your bootstrap server uri }
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer