apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-sample-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kustomize-sample-1
  template:
    metadata:
      name: kustomize-sample-1
      labels:
        app: kustomize-sample-1
    spec:
      containers:
        - image: nginxdemos/hello:plain-text
          name: nginx
          ports:
          - name: http
            containerPort: 80
            protocol: TCP