spring:
  profiles:
    active: local

---
server:
  port: 9001

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/async-saga
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: heedong
    password: 1q2w3e4r!@
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create